name: CI Backend

on:
  pull_request:
    branches:
      - development
      - master

jobs:
  lint-and-test:
    name: Lint and Test NestJS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: backend/nestjs/package-lock.json

      - name: Install dependencies
        run: npm install
        working-directory: backend/nestjs

      - name: Run linter
        run: npm run lint
        working-directory: backend/nestjs

      - name: Run tests
        run: npm test -- --passWithNoTests
        working-directory: backend/nestjs